language: java

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

script:
- ./gradlew test
- if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then ./gradlew -DdependencyCheck.failBuild=true dependencyCheckAnalyze; fi

after_success:
- ./gradlew jacocoTestReport
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    tags: true
    repo: hmcts/bulk-scan-ccd-event-handler-lib

- provider: releases
  api_key:
    secure: ZjR72S9DGG5wI6NjCbTGLBepOzSahG2k5ss1N0PuCzxAlK3tCBzahBvsvUA04SNb8+OapBOzL9hCuPTlw2/6HbNfOi1GFqHbLJgU7ALXBlYcMW1ZInVRbO5FPKevMHrsxgut/3sJnHVHXoNY+PViEyBFQer8W+Ajq/PDppBpZj2I9iHq/ZxPxgMfVbEF4iJmEfLDQv82M4yIVSYiDUPNgP2BvAhpmafXt/hqv1DjWUvzIruM8xBpFAbCgmIjoATf7ewbaHN6gpJw1uarmQp0gvjUOm7uTtSxHICkrV0dhAJIYPnD8ji94yWSt2CjhxQsm4w6sfk6slg5HD4G+o2wPfUiEo4hGUHV7rqUX52Qq6Rj8TVIzDgc5UjxNVFea5mlISH59ffWdBVcT6b7wetpL2w52dGt6iflK6zUkBvmjWaCoZIJpsKD9CIa2Y2fzEPxbCgSjCyM9o0okNEx6MkhMcqwmsR7D/DmhDd93ozRUabd5jYhWfICxywQAu9r0fDSL6yRkhniHbXG5M9LqpS4XcbklRMJDHvQNsUAdNT6T5dkb8AZkyUR9QgEXGhsvyrC1waRhttZCCNEBFgJwjBcPsul3iiIx7MhWlCzbGv/aCbwStV8GqGjNDH2A5oIaI1R3zEtX5pTiZWFuEA8fBff+dL/AWYNPUAZzzJR/vfcX6Q=
  file_glob: true
  file: build/libs/bulk-scan-ccd-event-handler-*.jar
  skip_cleanup: true
  on:
    repo: hmcts/bulk-scan-ccd-event-handler-lib
    tags: true

env:
  global:
  - secure: BbeRQZM7zzg5Z19mEREA56qmJWJ7MsZJAwfrZaEsIJuJcjC5wNplWSe+2WnDhfhkHxAg4uvQkuCACzQS70igl9CUzgKGUaGfMkbRZoCrA7jSvt2pKpiMkluymO/uPtY8uSN+jKAaZiGareW9U97doxrJpet+rnPthR/6zFHdT7hP8EaW8hmylfD2t0oSlYPmxk9mGe1vqHJbgWBrswLb4Ia/YRUpYo/4/xHnwKh5jmfSamBitR/pY9UFEjDZmJDJz0KW4VhYXy/4OVi8k2DfmKaN+Yw0c5uB0xFMb/ge9znDJtnKyREIyLToSWHrXF9ge/nAZ3ZTYpHBdfAGNoPlVXiul2UQ9hhGWOi+T/hPHXX2/GpbC344BO6NW+8ZwbGWftYItmBBg/dZex2mazS5hF0vKIQoGKaG8j63bAVetKY1ei9Zf+xUOST9LQHP1MGybXHWRMynruLnf6jldjyHAsTRDqaAW7XtP+Su53y+uAkg2v9FWGGk/UsuI0z9ujKqYQ+orSN2mlZmbAtGyjxxs7z5haDyZ56yUyL11bhrzoZuMwe4EXEqLW+8uQ0MLXOB/ot/To7iKZ8U4wHYjOIErxs6AoA8Qs01f68kB8i7ePfAnHWTzCWzy+m6pvHqd1eUhErquO4yHX/xBS5OmhW8F9z1x1Ns0Jmoph90JA12jXc=
  - secure: VcSN0gcoRjPRj/8H8GlLI2pvb/hjbIise18lUAYHoidj+plSP+5y2ixEPrAG593iMqKJtIMKtK7cGq07bScbvI66HiCqIcKh55q2zYO/kK/tG4dwxrrD6mFypTGl0XKsmyay7c2gFhBxkb8EMX1u6jxc3X21qMics7X6LaAcjkR1U3HeZPcF/noFQUcswcxpH4KxUQ+ddsKFwJFnBukLzwaT0xAofLntJ5hXzzhn5dS6OpdLq0dV3rHcV9a1OPeQqNjjVLtPsoH/k08NGgEY8rytYA6S+vRSuNr0L+TyhbGUdIXyZUTWx1qlvkrtmLKCU4U0QCVB+KEc/ya5yr5IJCIui1OpDA5ktSb1anXCKKeXBJak3nikDK4ijdwE9q88+/kCINQYjZGnc5jNRbjMBa6pl406adXL7aILajy2tx9krVQP7nofuRX/VuvAn+ipulLD2pujdNNbARPZQDd8y+pCtzmSwKCK7v5iG4c2Wl8dZ09pWkRArId58VynC8d2cbQgniQ8N+hRL3FK+SSVkaBK8xr3KgeOaC3m/dIFsOLcO9l86SiDXU88C4RsethDWwWNpt2oxv7Z4ASMvdBQSEvi4/a7n+cAp3cPe4vo/vNziiabWsCCgeAz6X2tZvE8aGfUFCUMx6NWrnW5Qffr2hhqOaGVE8L3XIhaCFaGD6o=
