language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew test"
- if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then ./gradlew -DdependencyCheck.failBuild=true
  dependencyCheckAnalyze; fi
after_success:
- "./gradlew jacocoTestReport"
- bash <(curl -s https://codecov.io/bash)
deploy:
- provider: script
  script: "./gradlew bintrayUpload"
  skip_cleanup: true
  on:
    tags: true
    repo: hmcts/bulk-scan-ccd-event-handler-lib
- provider: releases
  api_key:
    secure: ZjR72S9DGG5wI6NjCbTGLBepOzSahG2k5ss1N0PuCzxAlK3tCBzahBvsvUA04SNb8+OapBOzL9hCuPTlw2/6HbNfOi1GFqHbLJgU7ALXBlYcMW1ZInVRbO5FPKevMHrsxgut/3sJnHVHXoNY+PViEyBFQer8W+Ajq/PDppBpZj2I9iHq/ZxPxgMfVbEF4iJmEfLDQv82M4yIVSYiDUPNgP2BvAhpmafXt/hqv1DjWUvzIruM8xBpFAbCgmIjoATf7ewbaHN6gpJw1uarmQp0gvjUOm7uTtSxHICkrV0dhAJIYPnD8ji94yWSt2CjhxQsm4w6sfk6slg5HD4G+o2wPfUiEo4hGUHV7rqUX52Qq6Rj8TVIzDgc5UjxNVFea5mlISH59ffWdBVcT6b7wetpL2w52dGt6iflK6zUkBvmjWaCoZIJpsKD9CIa2Y2fzEPxbCgSjCyM9o0okNEx6MkhMcqwmsR7D/DmhDd93ozRUabd5jYhWfICxywQAu9r0fDSL6yRkhniHbXG5M9LqpS4XcbklRMJDHvQNsUAdNT6T5dkb8AZkyUR9QgEXGhsvyrC1waRhttZCCNEBFgJwjBcPsul3iiIx7MhWlCzbGv/aCbwStV8GqGjNDH2A5oIaI1R3zEtX5pTiZWFuEA8fBff+dL/AWYNPUAZzzJR/vfcX6Q=
  file_glob: true
  file: build/libs/bulk-scan-ccd-event-handler-*.jar
  skip_cleanup: true
  on:
    repo: hmcts/bulk-scan-ccd-event-handler-lib
    tags: true
env:
  global:
  - secure: lS8KuY/oVcWoYvjHCDEeEUBhU+Sz5dgEv61KnKw2uZtdFe2vpQi9dY3fO37Yzh4pUB3tmO5G0p7XfYrIq9j3G742N2o7ehPC0UwbTlCmuix9cIcRBaV3wX5Smn8niaR++10wFRNn0qsGVg5/isNLVlKeBDF+j6xf2lnRvedcdDgpKbw1YpFVtAdOg4rRtJjS8rbYuhE8HPoQEeRHz2Zv4fNNQQK3fEtP5Na5v7MWTOzOmFK/lm7BZ3kqwJbKd8GdArdIM7LJlVD5rLHrhgniJ8VpvpZlUEiCsbY8WqWe4WiljtGGM6MURPa0glEUvCQ5UqIsPOY4wXaO8H1YGBTafaC2hCj26pgr/A4gdWjsG3IknKRZgBlGCMERWmxv+1+vS36n1faJOXtdBmHjFYsN9VELVDDoAYJTzUoROQoF70Y/QunkKOJwu0MDl14pVm7hnwoyO4i6fACjDFlZYZukhCzWNqHnGbFml6DFMdJSF3vETZaPIE87cEgNjsXNuTV0nBjziN4CWr3Pi5LLnH3QmDSoApgWc4K1KtyZtsQVHHiZYm37i/oPjEYXX9SismsEdiAuDsr5VgpPQNqG76Ug5UZIxQvZDjh7wLVcUaqPUQOdgYFSHlI+EHJMD04zuq3noqLbia/h+NLhZa+ulNM2c5IQctcv1vP9B8Tod8zFfkg=
  - secure: EwES06LogP5agqI7mf3Z9E8PQPCzQi3IVZ1Gc9Cenjd1WlDNbVvQupXP6D1gTeUbvLSgfV0JImN8R46Ieplnk+hRgnwVm5J3Jt660SjlHhGuhBwLWZ6KVjE2f0xwY4r2o0/QAHKCnAbGsa3k0576h0jwQy+9wcpoScdk2YeBCmZWAOtTRKTMYrNwZyy0A7Kp6AocrzgfWD7NrsxN/yo8I4n1dwHs+jQnga2OTSwxXigGgi0zf8Pxne8IXUh/WSrUVhLpzRwZQA7dxqE5yw70yVRmoNYHS/93aj6tGWl/Z/in9dwDY+Aq8JAfKnTyV8j52sdT+CoWs+RrYCW+t6pGGXRdOBedJI/koSL63V1YieuqxkFoZLoTDZdrhSYCTAiEvbijRAwQEqBAnHf246DcMgpM4ee8yI9f2PRgydw7A5iD+hIokwETip6Vwo12Nd1JRKRtJxcsG7Hl8Alr2hfKzpJCa7veuN4g6cyBparuuHmlPjN7fOIMVrDy1VIUX0FplLSUO42q/GR1v6G7xYtMbuUlf8c6jmV5QoicFm06vrDA82XG/TtBtMcHtWLYzyGxTJi+8crggpegmaYphMYeXAkxue17VLP6P5GQMjuJ4HGQp8+a3d0AEuKkTT9zBgGiT9G2tMSWjC29hEaM2Yz1l5/TO+JcQRJEcBbi43QXEYg=
